id: cover_up_at_2100
alias: "Bring Up Covers at 21:00"
description: "Opens all covers at 21:00."
trigger:
  - platform: time
    at: "21:00:00"
condition: []
action:
  - service: script.set_cover_position_up
mode: single
